### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by S1SYPHOS** [afbora/kirby-broken-links-checker#1]
Hey there @afbora!

Recently I created a Kirby CLI command to check broken links and wanted to release it as standalone package, but now I thought "why not open a PR and see what happens" .. you could check it out and if it's not for you, or whatever, no hard feelings 😅 

Let me know what you think,
Martin

PS: only external dependency (besides getkirby/cli) is Guzzle, which is part of Kirby anyway? Don't remember ..

**Comment by afbora** [comment]
@S1SYPHOS Sorry, I don't understand what you mean. You want to release a new command plugin that checks for broken links?

**Comment by CHE1RON** [comment]
I've created a command for `getkirby/cli` which 
1. collects links from all pages
2. checks & reports which ones are broken
and I wondered if you would consider merging my code into this plugin - since it does essentially the same thing 😄

**Comment by S1SYPHOS** [comment]
I thought about creating a PR, merging my CLI command into your package - does that sound good to you? 😅

**Comment by afbora** [comment]
Ohh, I'm always grateful for contributions 🙏 @S1SYPHOS

**Comment by S1SYPHOS** [comment]
I'll contribute something from my work account later today, gotta check if it needs polishing first 😆

**Comment by S1SYPHOS** [comment]
Well, it took me a while, but here it is: #2

**Comment by S1SYPHOS** [comment]
Hey @afbora Let me know if you don't want this PR to be merged, then I'll release it as separate plugin - but I think it would be a nice addition 😕

**Comment by S1SYPHOS** [comment]
@afbora Anything I can do to help get this merged? :confused:
